neoxis_news:
    resource: "@NeoxisBundle/Resources/config/routing/news.yml"
    prefix:   /news

neoxis_actupage:
    path:     /actu
    defaults: { _controller: NeoxisBundle:Front:actu }

neoxis_contact:
    path:     /contact
    defaults: { _controller: NeoxisBundle:Front:contact }

neoxis_notre_expertisepage:
    path:     /notre_expertise
    defaults: { _controller: NeoxisBundle:Front:notre_expertise }

neoxis_nos_engagementspage:
    path:     /nos_engagements
    defaults: { _controller: NeoxisBundle:Front:nos_engagements }

neoxis_logiciels_referencespage:
    path:     /logiciels_references
    defaults: { _controller: NeoxisBundle:Front:logiciels_references }

neoxis_societepage:
    path:     /societe
    defaults: { _controller: NeoxisBundle:Front:societe }

neoxis_mention_legalespage:
    path:     /mention_legales
    defaults: { _controller: NeoxisBundle:Front:mention_legales }

neoxis_neo_homepage:
    path:     /
    defaults: { _controller: NeoxisBundle:Front:neo_home }

neoxis_swiftmailer:
    path:     /swiftmailer
    defaults: { _controller: NeoxisBundle:Back:swiftmailer }





